APP_NAME = "ClipScope"
APP_VERSION = "0.1.5"
DEFAULT_DATABASE_FILENAME = "clipscope.db"
DEFAULT_PLAYER_PATH = "/obs-player"
DEFAULT_TWITCH_CLIENT_ID = "tjsgrpvb9itt6wnfbybser23ga9aku"
UPDATE_INFO_URL = "https://raw.githubusercontent.com/heconis/ClipScope/main/version.json"
DEFAULT_RELEASES_URL = "https://github.com/heconis/ClipScope/releases"
KOFI_SUPPORT_URL = "https://ko-fi.com/heconis"
